### DISCUSSION TITLE
Conditional spawner-upgrades

### DISCUSSION THREAD

**Discussion by Aathoss** [OmerBenGera/WildStacker#429] [Pending Feature Requests]
Hey,
Being able to set conditions for players to upgrade **'requirements'**.
Because currently on my skyblock server I would like to be able to control the improvement of the spawner thanks to the placeholder, since the command available in superiorskyblock2 `/is admin setspawnerrates` does not work with WildStacker spawners

Example :
- permissions
- javascript (to check placeholder conditions)
- regex matches
- comparators
- etc...

```
        coal:
          id: 1
          next-upgrade: iron
          min-spawn-delay: 160
          max-spawn-delay: 700
          required-player-range: 20
          spawn-range: 5
          spawn-count: 8
          max-nearby-entities: 7
          display: '&7 (&8Coal&7)'
          cost: 1000
          requirements:
            placeholder:
              type: javascript
              expression: '%prestige_level% >= 1'
          icon:
            type: COAL
            name: '&8Coal'
            lore:
            - '&8This upgrade costs $%cost%'
            - '&7 '
            - '&7Spawn Delay Range&f: &8%min-spawn-delay%-%max-spawn-delay%'
            - '&7Spawn Count&f: &8%spawn-count%'
            - '&7Max Nearby Entities&f: &8%max-nearby-entities%'
            - '&7Required Player Range&f: &8%required-player-range%'
            - '&7Spawn Range&f: &8%spawn-range%'
```
