### DISCUSSION TITLE
Merge flying entities from spawner ignoring the `stack-down` setting

### DISCUSSION THREAD

**Discussion by Aeyos** [OmerBenGera/WildStacker#621] [Pending Feature Requests]
From https://github.com/BG-Software-LLC/WildStacker/issues/620

Make flying entities spawned from a spawner merge together without needing to disable the `stack-down` feature. To solve this issue:

![image](https://user-images.githubusercontent.com/4277681/192113845-59e0fa6e-cb83-48df-8d28-592818fc2394.png)

The config section had to be modified

```
  stack-down:
    # Should the stack-down feature be enabled on the server?
    enabled: false
    # A list of entities that will be forced to only stack down.
    # You can combine filters using "ENTITY_TYPE:SPAWN_REASON"
    stack-down-types:
    - BLAZE
    - GHAST
```

It'd be more intuitive if the spawner merging logic ignored this setting and merged ghasts and blazes into a single stack by default
