### ISSUE TITLE
Creeper nerf doesn't work by SPAWNER_EGG

### ISSUE THREAD

**Issue by SnaiilGaming** [OmerBenGera/WildStacker#29]
Hello,
I have a problem with the creeper nerf by Spawner_Egg. Indeed, it seems that the feature does not work with creepers. As much as I've tried with zombies and skeletons in particular, it works fine, but with the creeper it doesn't work. The creeper continues to move, focus the players and even explodes.

**This is my config from WildStacker :**
```yml
  nerfed-entities:
    # A list of entities that will be nerfed.
    # If you want all entities to be nerfed, set this to [].
    whitelist:
    - BLAZE:SPAWNER
    - CAVE_SPIDER:SPAWNER
    - CREEPER:SPAWNER
    - CREEPER:SPAWNER_EGG
    - ENDERMAN:SPAWNER
    - IRON_GOLEM:SPAWNER
    - SKELETON:SPAWNER
    - MAGMA_CUBE:SPAWNER
    - PIG_ZOMBIE:SPAWNER
    - ZOMBIE:SPAWNER
    - SPIDER:SPAWNER
    - SKELETON:SPAWNER_EGG
    # A list of entities that won't be nerfed.
    blacklist: []
    # A list of worlds that entities can be nerfed in.
    # If you want entities to be nerfed inside all worlds, set this to [].
    worlds: []
    # Should nerfed entities be able to teleport?
    teleport: false
```

As you can see on the video, the creeper is well indicated as a nerfed but you can see it explodes anyway (You can't see it on the video but it moves and focuses the players)
https://user-images.githubusercontent.com/65194325/106359728-c3c69800-6314-11eb-80be-c7424af234c2.mp4
