### ISSUE TITLE
Statistics  menu unable

### ISSUE THREAD

**Issue by Redstylt** [OmerBenGera/WildStacker#54]
If you disable both menus (amount and upgrade), you can see the statistics anymore. The manage menu doesnt show up anymore.
Also would be great to be able to choose what can activate this menu. (not only shift click)

MC version : 1.16.5
WS version : 69
SS2 version : 68

```
  # Settings related to the manage menu of spawners.
  # If all the sub menus are disabled, the manage menu will not be opened.
  manage-menu:
    # Should the amounts menu be enabled?
    amounts-menu: false
    # Should the upgrades menu be enabled?
    upgrade-menu: false
```
